// 막대그래프 데이터(데이터 세트)
var dataSet = [300, 130, 5, 60, 240];
// 데이터를 기반으로 그리기
d3.select("#myGraph")
	.append("rect")
	.attr("x", 0)
	.attr("y", 25)
	.attr("width", dataSet[0])
	.attr("height", "20px")
d3.select("#myGraph")
	.append("rect")
	.attr("x", 0)
	.attr("y", 50)
	.attr("width", dataSet[1])
	.attr("height", "20px")
d3.select("#myGraph")
	.append("rect")
	.attr("x", 0)
	.attr("y", 150)
	.attr("width", dataSet[2])
	.attr("height", "20px")
d3.select("#myGraph")
	.append("rect")
	.attr("x", 0)
	.attr("y", 100)
	.attr("width", dataSet[3])
	.attr("height", "20px")
d3.select("#myGraph")
	.append("rect")
	.attr("x", 0)
	.attr("y", 125)
	.attr("width", dataSet[4])
	.attr("height", "20px")
